version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
